apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: springbootapps.sparky.com
spec:
  group: sparky.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                ports:
                  type: object
                  additionalProperties:
                    type: integer
                replicas:
                  type: integer
                  minimum: 1
                resources:
                  type: object
                  properties:
                    cpuRequest:
                      type: string
                    memoryRequest:
                      type: string
                    cpuLimit:
                      type: string
                    memoryLimit:
                      type: string
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    engine:
                      type: string
                    instanceClass:
                      type: string
                    allocatedStorage:
                      type: integer
                    masterUsername:
                      type: string
                monitoring:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    grafanaDashboardTemplate:
                      type: string
              required:
                - image
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                createdResources:
                  type: array
                  items:
                    type: string
                databaseId:
                  type: string
                databaseEndpoint:
                  type: string
  scope: Namespaced
  names:
    plural: springbootapps
    singular: springbootapp
    kind: SpringBootApp
    listKind: SpringBootAppList