apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparky-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sparky-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sparky.com
  resources:
  - springbootapps
  - springbootapps/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sparky-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sparky-operator
subjects:
- kind: ServiceAccount
  name: sparky-operator
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparky-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sparky-operator
  template:
    metadata:
      labels:
        name: sparky-operator
    spec:
      serviceAccountName: sparky-operator
      containers:
      - name: sparky-operator
        image: sparky/sparky-kubernetes-operator:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key